Friday Review Session
=====================

### Variables:

In [3]:
# A variable is like a storage box to pull information.
# Whenever you want to refer to that information, just call the name of the variable

name = 'Gabby' #String
age= 20 #Integer
is_student = True #boolean



In [4]:
#Difference between = & ==
x1 = 20 # = is an assignment operator, so it assigns value. It means "x is now 20".

 # == checks if two things are equal to eachother
x = 4
y = 4
if x == y: 
    print('They are equal')
else:   
    print('They are not equal')

They are equal


### How to print variables in a statement

In [5]:
#How to print variables in a statement

name = 'Darius'

#You can use + or , to join two nstatements together and variablesn in a print statement
print("Hello" + name) # With +, you have have to add space
print("Hello " + name)# With , it adds spaces inbetween for you
print ("Hello", name)
print("Hello Darius")

HelloDarius
Hello Darius
Hello Darius
Hello Darius


### If Statements:
If statements and conditionals let your code make decisions

If a Condition is true, run this part of the code

If it is fales, run a different poart of code

In [6]:
if condition:
    # code if the condition is true will run
elif another_code:
    # code if first condition is false, and this other condition is true will run
else:
    # code if none of the above are true

IndentationError: expected an indented block after 'if' statement on line 1 (2033062477.py, line 3)

### Nested If Statements 
(if inside of an if)

In [ ]:
if condition:
    if another_condition:
        # Code will run BOTH if statements are true
else:
    # Code will run if first if statement is not true

In [ ]:
# example with numbers
temperature = 65

if temperature > 85:
    print ("It's Hot")
elif temperature >=60:
    print("Its's Nice!")
else:
    print("It's Cold")

In [ ]:
Different Symbols:

> greater than
< less than
>= greater than or equal to
<= less than or equal to
% modules ... tells you the remainder after dividing.
    5 % 2 = 1
    4 % 2 = 0
== is equal to
!= is not equal to
& and, for doing two conditions
| or
    ex: condition & other_condition | another_condition

### Example problem:
Make a variable called _grade_, and assign it a value of 85.

If grade is greater than or equal to 90, Print A.

If grade is greater than or equal to 80, Print B.

If grade is greater than or equal to 70, Print C.

If none of these, print fail




In [ ]:
grade = 80

if grade>=90:
    print("A")
elif grade>=80:
    print("B")
elif grade>=70:
    print("C")
else:
    print("fail")
    

### While Loops

While looks basically tell the computer to run a piece of code as long as a certain condition is true 

Think of it like: "Keep doing this code while this is true"


In [ ]:
count = 1

while count <= 5:
    print("Count is:", count)
    count = count + 1 
# updating the variable is very important so we dont run into infinite loops

In [ ]:
password = "hello"

while password != 'hello': # While password does not equal 'hello', say incorrect and promt to enter the password again
    print('Incorect password')
    password = input('Enter the password: ')
print('Access granted')

### For Loops

Similar to while loop in sense that it repeats code.

A for loop goes through items in a list or range, and runs code for each item.


### First way: Traverse through a list

In [ ]:
fruits = ['apple','orange','banana']
for x in fruits: # For each
    print('I like', x)

### Second way: Using range function

range(n) gives you a list of numbers 0 to n-1

In [ ]:
for num in range(5):
    print(num)

### Third way: Using range function but choosing where to start and stop
range(start, stop)

In [ ]:
for x in range(1,4):
    print(x)

### Forth way:
range(start, stop, step)

In [ ]:
for x in range (2, 11, 2):
    print(x)

### Functions
A function is a reusable recipe.

You write and define the function once, and then use it whenever you need it.

When I call this function, I run these steps.

In [ ]:
#create a function
def say_hello():
    return 'Hello!'

In [ ]:
#Use function
print(say_hello())

In [ ]:
#Create a function
def greet(name):
    greeting = "Hi " + name + "! Welcome!"
    return greeting

In [ ]:
#Call the Function
print (greet("Belle"))
print (greet("Daniel"))

In [ ]:
#Create a function
def is_even(number):
    if number % 2 == 0: # Mod 2 means the remainder when dividing by 2
        return True 
    else:
        return False

In [ ]:
# Using a function
print(is_even(36))

# Can be put into a variable first
is_33_even = is_even(33)
print(is_33_even)

### Multiple Inputs:

In [ ]:
def total_flowers_cost(amount_of_flowers, price_of_flowers):
    total_cost = amount_of_flowers * price_of_flowers
    return total_cost

In [ ]:
Amel = total_flowers_cost(3,12)
print("Amel spends $" , Amel , "on flowers")

Belle = total_flowers_cost(4,10)
print("Belle spends $" , Belle , "on flowers")

### Numpy Library:
numpy is a helful library when working with numbers and arrays

Array = list

In [ ]:
import numpy as np

### Arrays:

In [ ]:
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

In [ ]:
print(my_array.size) #Shows how many items are in your array

In [ ]:
my_array_doubled = my_array * 2 # Multiplies an entire array / list
print(my_array_doubled)

### Indexing:

In [ ]:
first_item = my_array[0]
print(first_item)

In [ ]:
print(my_array[2]*3)

In [ ]:
print(my_array[:3]) #print first 3 items of array 

In [ ]:
print(my_array[1:4]) # print item 1 through 4

### 2D Arrays:
Think of 2D arrays as like a table. Three will be rows and columns

In [ ]:
my_2D_array = ([1, 2, 3], [4, 5, 6], [7, 8, 9])
print(my_2D_array)

In [ ]:
my_2D_array = np.zeros((3,4)) #3 rows and 3 columns
#print(my_2D_array)

my_2D_array[0,0] = 4 # changeone number
print(my_2D_array)
print()

my_2D_array[1] = 4 # change whole row
print(my_2D_array)
print()

my_2D_array[:, 2] = 4 # change whole column
print(my_2D_array)
print()

To generate a random number we use the random.randint(a,b) function.

generates a random number from a to b

In [ ]:
random_num = np.random.randint(0,6)
print(random_num)

To generate a random choice from a list, we use np.random.choice(list)

In [ ]:
lunch_options = ['Mac & Cheese', 'Pizza', 'Salad']
what_will_i_eat = np.random.choice(lunch_options)
print(what_will_i_eat)

### Boolean Arrays:
Boolean is True(1) or False (0)

In [22]:
import numpy as np
cat_colors = np.array(['brown', 'black', 'black', 'grey', 'white', 'orange', 'black'])
cat_names = np.array(['nemo', 'lady', 'simba', 'tramp', 'snow', 'kitty', 'star'])

In [23]:
black_color = cat_colors == 'black' #name of my boolean array; set condition on right side
black_color

array([False,  True,  True, False, False, False,  True])

In [24]:
# use boolean array to pull out other data that correspons to True
black_cats_bol = cat_names[black_color] #original data[boolean array]
black_cats_bol

array(['lady', 'simba', 'star'], dtype='<U5')

In [25]:
#another example

food = np.array(['pizza', 'pizza', 'orange', 'chips', 'grape', 'cheese'])
cost = np.array([2,3,5,6,1,4])

#pull cost of all pizza
pizzas = food == 'pizza'
pizza_cost = cost[pizzas]
pizza_cost

array([2, 3])

In [28]:
#one more example

price = np.array([23,45,100,34,12])
weight = np.array([13,14,15,16,17])

#pull price of everything that weights more than 15

heavy = weight > 15 #boolean_array = (condition)
price_heavy = price[heavy]
price_heavy

array([34, 12])

### Matplotlib:
Libraries = a collection of a bunch of functions. You need to import a library if you want to use it's function

Matplotlab is a specific libray that people use to make plots and graphs 

We habve been using the pyplot section of Matplotlib

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
list_1 = [1, 2, 3, 4]
list_2 = [10, 20, 30, 40]

plt.plot(list_1, list_2, color = 'palevioletred', linestyle = '--', linewidth = 5) # create a plot
plt.title("My Plot")
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.show()

In [ ]:
list_1 = [1, 2, 3, 4]
list_2 = [10, 20, 30, 40]

plt.plot(list_1, list_2, color = 'orchid', marker = 'o',markersize = 8, markerfacecolor = 'purple') # create a plot and customize
plt.title("My Plot")
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.grid(True)
plt.show()

### Bar Plots:

used for when you have one numerical dataset and one categorical dataset

In [ ]:
#Sample data
categories = ['apples', 'bananas', 'cherries'] #categories always x axis
values = [10, 24, 18]  #numbers always y axis
colors = ['red', 'yellow', 'pink']

plt.bar(categories, values, color = colors) # making each bar a seperate color
plt.title('Fruit Sales')
plt.xlabel('Fruits')
plt.ylabel('Number Sold')

### Histograms:

Histograms look similiar to bar plots but are used to group NUMERIC data into bins (ranges) and show how many fall into tht range

In [ ]:
#example data of scores
scores = [85, 87, 70, 91, 88, 73, 74, 90, 95, 85, 78, 82, 88, 84, 79, 87, 89]

plt.hist(scores, bins = 5, color = 'darkseagreen', edgecolor = 'black')
plt.title('Distribution of Test Scores')
plt.xlabel('Score Ranges')
plt.ylabel('Number of Students (Frequecy)')
plt.show()

### Scatter plots:

shows relationships between two sets of numbers. Each point represents one data point. Similar to line plots but without the line.

In [ ]:
hours = [1, 2, 3, 4, 5, 6]
scores = [50, 55, 65, 70,75, 85]

#How many hours a student vs test score
plt.scatter(hours, scores, color = 'salmon') #(x,y)
plt.title('Hours Studied vs. Test Scores')
plt.xlabel('Hours studies')
plt.ylabel('Test Scores')
plt.grid(True)

### Subplots In Matplotlib:

Multiple plots in one figure.

In [ ]:
#Sample Data 

#1st Subplot
x_sub1 = [1,2,3,4]
y_sub1 = [2,4,6,8]

#2nd Subplot
x_sub2 = ['Apples', 'Bananas', 'Cherries']
y_sub2 = [6, 8, 10]

plt.subplot(1, 2, 1) # (rows, columns, which number plot you want to create)
plt.plot(x_sub1, y_sub1, colo = 'skyblue', marker='o', markerfacecolor = 'c')
plt.annotate("Peak", arrowprops = dict(facecolor = 'darkblue'), xy = (4,8), xytext = (3,8))
plt.title('1st Subplot')
plt.xlabel('x data')
plt.ylabel('y data')

colors = ['red', 'yellow', 'pink']
plt.subplot(1, 2, 2) # (rows, columns, and now i want to make the second plot)
plt.bar(x_sub2, y_sub2, color = colors)
plt.title('Fruitsb Sold')
plt.xlabel('Fruits')
plt.ylabel('Number Sold')

plt.tight_layout() # fixes layout

### Pandas

library for whenever you are working with data sets/ data frames

In [ ]:
import pandas as pd # imports the library

In [ ]:
df = pd.read_csv("new_file.csv") #import a data frame from your computer

df.to_csv("new_file.csv", index = False) #save data frame to your computer

# index = False means it wont save row numbers as seperate columns

In [ ]:
print(df)

In [ ]:
first_row = df.iloc[0] #calling a function 
print(first_row)

In [ ]:
subset_rows = df.iloc[0:2] #iloc = integer locaion
                           #[columns, rows]
print(subset_rows)

In [ ]:
filtered_data = df[df['Price'] > 600]
print(filtered_data)

In [ ]:
filtered_data2= df [(df['Price'] >600) & (df['Quantity'] < 80)]
print(filtered_data2)

### Adding & Removing Columns in a Data Frame

In [ ]:
df['Discount'] = [10, 15, 20] # add in a column
print(df)

df.drop('Discount', axis = 1, inplace = True) # remove a column  #axis = 1: remove column
print(df)

df.drop(0, axis = 0, inplace = True) #delete row


### How to plot in Pandas with Data Frames

In [ ]:
# this is how you plot in matplotlib
data1 = [1,2,3,4]
data2 = [2,3,4,5]
plt.plot(data1, data2, color = 'green')

# here is the diff with plotting in pandas:
# you write x = and y =
df.plot(x='Price', y = 'Quantity', kind = 'line', color = 'blue')


In [ ]:
# kind = 'bar'
plt.hist(df['Price'], bins = 15)